---
- name: ensure redis configuration
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_conf_file }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0640
  become: true
  register: redis_conf_file_state
