---
- name: ensure systemd service
  include_role:
    name: "damex.systemd_service"
  vars:
    systemd_service_name: "{{ redis_service_name }}"
    systemd_service_restart_on: "{{ redis_conf_file_state.changed }}"
